version: "3.9"

services:
  database:
    image: mariadb:11.3.2
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
    ports:
      - "${DB_ADDR}:3306"
    volumes:
      - "${STORAGE_DB_PATH}:/var/lib/mysql"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "${PMA_ADDR}:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: database
      PMA_USER: "${DB_USER}"
      PMA_PASSWORD: "${DB_PASS}"
    depends_on:
      - database
