services:
  web:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    configs:
      - source: nginx_cfg
        target: /etc/nginx/conf.d/default.conf
    volumes:
      - ./client/build:/var/www/html
      - ./storage/logs/nginx:/var/log/nginx

  database:
    image: mariadb:11.3.2
    environment:
      MYSQL_USER: terminal_chat
      MYSQL_PASSWORD: terminal_chat
      MYSQL_DATABASE: terminal_chat
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ./storage/databases/mariadb:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: database
      PMA_USER: terminal_chat
      PMA_PASSWORD: terminal_chat
    depends_on:
      - database

configs:
  nginx_cfg:
    file: ./configs/nginx/default.conf
