services:
  database:
    image: mariadb:11.3.2
    environment:
      MYSQL_USER: terminal_chat
      MYSQL_PASSWORD: terminal_chat
      MYSQL_DATABASE: terminal_chat
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./storage/databases/mariadb:/var/lib/mysql
    networks:
      - app
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      PMA_HOST: database
      # PMA_USER: terminal_chat
      # PMA_PASSWORD: terminal_chat
    depends_on:
      - database
    networks:
      - app
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  server:
    image: local/terminal_chat_server:latest
    ports:
      - 3000:3000
      - 3001:3001
    depends_on:
      - database
    volumes:
      - ./server:/app
    networks:
      - app
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  client:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    depends_on:
      - database
      - server
    volumes:
      - ./client/build:/var/www/html
      - ./storage/logs/nginx:/var/log/nginx
    configs:
      - source: nginx_cfg
        target: /etc/nginx/conf.d/default.conf
    networks:
      - app
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

configs:
  nginx_cfg:
    file: ./docker/nginx/configs/default.conf

networks:
  app:
